mutation RegisterAccount(
    $email: String!, 
    $password: String!,  
    $firstName: String!, 
    $lastName: String!, 
    $acceptsMarketing: Boolean = false,
) {
    customerCreate(input: {
        email: $email, 
        password: $password, 
        firstName: $firstName, 
        lastName: $lastName,
        acceptsMarketing: $acceptsMarketing, 
    }) {
        customer {
            id
        }
        customerUserErrors {
            code
            message
        }
    }
}
