{
  menu(handle: "home-slider") {
      handle
      items{
          id
          title
          url
          type
          resource{
            ...on Product{
                handle
                images(first: 1){
                    edges{
                        node{
                            url
                            altText
                        }
                    }
                }
            }
          }
      }
  }
}